Updated wording on FAQ
HackCU/HackCU pull request #28
Opened 2017-12-07 22:36 UTC by OliverCollins

## What this PR does / why we need it

A few sentences describing the overall goals of the pull request's commits.

## Related Issues

Fixes #

## Some questions

- [ ] I have read the contributing guidelines
- [ ] I abide by this repository Code of Conduct

## Special notes for your reviewer

(optional)

## Additional Notes

Do you want to add anything else? We :heart: to hear your opinions!

2017-12-07 23:25 UTC, AparaV requested changes
Also, adding a description about what this PR does helps! 🙃

2017-12-07 23:25 UTC, AparaV commented on _data/faq.yaml
> +  answer: "Absolutely not! It doesn’t matter if you are a designer, a writer, or a chemist. There is a place for you here. Prior to hacking, there will be a team formation session at the beginning of
`Prior to hacking, [...] at the beginning of the event [...]` - Can you remove one of those?

2017-12-08 02:30 UTC, casassg commented
Also, I would appreciate if you fill the description of the PR next time @OliverCollins

2017-12-08 02:32 UTC, casassg requested changes
Holding this at least until next meeting to decide on this. Otherwise, it should be removed to a more agnostic answer

2017-12-08 02:32 UTC, casassg commented on _data/faq.yaml
> +  answer: "Yes! Travel reimbursement will be based on a case-by-case basis. Stay tuned for more details!"
Also, this needs to be specified at next meeting.

2017-12-23 18:10 UTC, casassg approved these changes
updated to have it merged myself

2017-12-23 22:57 UTC, AparaV approved these changes

2017-12-23 23:05 UTC, merged