Made beacon.io bigger
HackCU/HackCU pull request #55
Opened 2018-02-06 19:23 UTC by carlcortright

## Makes the Beacon.io logo bigger

The business school asked for this. Leaving it at the bottom but making it larger on screen. Thoughts? Can also tell them that it need to stay small. 

The logo itself is a higher res one they got from the company, so we should keep that. 

## Some questions

- [ ] I have read the contributing guidelines
- [ ] I abide by this repository Code of Conduct

2018-02-06 22:59 UTC, casassg requested changes
This doesn't exist. The file is a png. Did you forget to commit the new file?

2018-02-07 00:16 UTC, carlcortright commented
Hey the file they gave us is jpg, unfortunately, do I need to convert?

2018-02-07 00:54 UTC, casassg commented
What I mean is that this jpg does not exist in the repository which in turn produces this (check beacon.io image doesn't exist). Also, for transparency, we need to do it on png as jpg doesn't accept transparencies.  
![screencapture-localhost-4000-1517964797807](https://user-images.githubusercontent.com/6912589/35892456-a58dfbb6-0b66-11e8-8f97-1bde3efc926e.png)

2018-02-07 00:55 UTC, casassg commented
Also, I can make a PR making it slightly bigger.

2018-02-07 00:59 UTC, casassg commented
See #56 for the proposed alternative

2018-02-10 03:19 UTC, casassg commented
Closing this.

2018-02-10 03:19 UTC, closed without merging